export const ActivityEventCodes = {
  // Admin - Booking Management
  ADMIN_BOOKING_CREATED: "ADMIN_BOOKING_CREATED",
  ADMIN_BOOKING_UPDATED: "ADMIN_BOOKING_UPDATED",
  ADMIN_BOOKING_CANCELLED: "ADMIN_BOOKING_CANCELLED",
  ADMIN_BOOKING_VIEWED: "ADMIN_BOOKING_VIEWED",
  ADMIN_BOOKING_COMPLETED: "ADMIN_BOOKING_COMPLETED",
  ADMIN_BOOKING_REASSIGNED: "ADMIN_BOOKING_REASSIGNED",
  ADMIN_BOOKING_APPROVED: "ADMIN_BOOKING_APPROVED",
  ADMIN_BOOKING_REJECTED: "ADMIN_BOOKING_REJECTED",
  ADMIN_TRANSACTION_FLAGGED: "ADMIN_TRANSACTION_FLAGGED",

  // Admin - Itinerary Management
  ADMIN_ITINERARY_STANDARD_CREATED: "ADMIN_ITINERARY_STANDARD_CREATED",
  ADMIN_ITINERARY_UPDATED: "ADMIN_ITINERARY_UPDATED",
  ADMIN_ITINERARY_DELETED: "ADMIN_ITINERARY_DELETED",
  ADMIN_ITINERARY_DRAFT_SAVED: "ADMIN_ITINERARY_DRAFT_SAVED",
  ADMIN_ITINERARY_SENT: "ADMIN_ITINERARY_SENT",
  ADMIN_ITINERARY_DRAFT_DELETED: "ADMIN_ITINERARY_DRAFT_DELETED",

  // Admin - User Management
  ADMIN_USER_CREATED: "ADMIN_USER_CREATED",
  ADMIN_USER_DELETED: "ADMIN_USER_DELETED",
  ADMIN_USER_ROLE_UPDATED: "ADMIN_USER_ROLE_UPDATED",
  ADMIN_USER_PASSWORD_RESET: "ADMIN_USER_PASSWORD_RESET",
  ADMIN_USER_SUSPENDED: "ADMIN_USER_SUSPENDED",
  ADMIN_USER_BANNED: "ADMIN_USER_BANNED",

  // Admin - System & Reports
  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_REPORT_EXPORTED: "ADMIN_REPORT_EXPORTED",
  ADMIN_REPORT_VIEWED: "ADMIN_REPORT_VIEWED",
  ADMIN_NOTIFICATION_SENT: "ADMIN_NOTIFICATION_SENT",
  ADMIN_PROFILE_UPDATED: "ADMIN_PROFILE_UPDATED",
  ADMIN_SYSTEM_CONFIG_UPDATED: "ADMIN_SYSTEM_CONFIG_UPDATED",

  // User - Booking & Transactions
  USER_BOOKING_CREATED: "USER_BOOKING_CREATED",
  USER_BOOKING_CANCELLED: "USER_BOOKING_CANCELLED",
  USER_PAYMENT_COMPLETED: "USER_PAYMENT_COMPLETED",
  USER_INVOICE_DOWNLOADED: "USER_INVOICE_DOWNLOADED",
  USER_REFUND_REQUESTED: "USER_REFUND_REQUESTED",

  // User - Travel Plans
  USER_TRAVEL_PLAN_CREATED: "USER_TRAVEL_PLAN_CREATED",
  USER_TRAVEL_PLAN_UPDATED: "USER_TRAVEL_PLAN_UPDATED",
  USER_TRAVEL_PLAN_DRAFT_SAVED: "USER_TRAVEL_PLAN_DRAFT_SAVED",
  USER_TRAVEL_PLAN_COLLABORATOR_ADDED: "USER_TRAVEL_PLAN_COLLABORATOR_ADDED",
  USER_TRAVEL_PLAN_COLLABORATOR_REMOVED: "USER_TRAVEL_PLAN_COLLABORATOR_REMOVED",
  USER_TRAVEL_PLAN_DELETED: "USER_TRAVEL_PLAN_DELETED",

  // User - Inquiries & Support
  USER_INQUIRY_SUBMITTED: "USER_INQUIRY_SUBMITTED",
  USER_INQUIRY_CREATED: "USER_INQUIRY_CREATED",
  USER_SUPPORT_REPLIED: "USER_SUPPORT_REPLIED",

  // User - Engagement & Feedback
  USER_TRIP_REVIEWED: "USER_TRIP_REVIEWED",
  USER_FEEDBACK_SUBMITTED: "USER_FEEDBACK_SUBMITTED",
  USER_ITINERARY_VIEWED: "USER_ITINERARY_VIEWED",
  USER_ITINERARY_SHARED: "USER_ITINERARY_SHARED",

  // User - Account & Security
  USER_LOGIN: "USER_LOGIN",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
  USER_2FA_ENABLED: "USER_2FA_ENABLED",
  USER_2FA_DISABLED: "USER_2FA_DISABLED",
} as const;

export type ActivityEventCode =
  (typeof ActivityEventCodes)[keyof typeof ActivityEventCodes];
